#!/bin/bash

#
# showHelp
#
function showHelp {
  name=$(basename $0)
  echo ""
  echo ""
  echo "usage : $name <comand> <args>"
  echo ""
  echo "Commands :"
  echo ""
  echo "  $name create <params>   : create a multisite drupal project for development. You have to git init, commit and push your project to save it after create "
  echo "  $name checkout <params> : get an already created multisite drupal project from a git for development or production (TODO)"
  echo "  $name site create <params>  : create and install a new website in the project."
  echo "  $name site install <params> : install a site already created for development after a git clone of the project"
  echo "  $name site build <params>  : compil and build a site frontend"
  echo "  $name package : create a package for deployment in production of a project"
  echo "  $name site package : create a package for deployment in production of a project"
  echo "  $name update  : update the project in production or dev"
  echo "  $name site update  : update a site in production or dev"
  echo ""
  echo ""
  exit 1
}

#
# checkGit
#
function checkGit {
  if ! command -v git >/dev/null 2>&1; then
    echo ""
    echo ""
    echo "git must be installed and define in the \$PATH variable"
    echo ""
    echo ""
    exit 1
  fi
}

#
# checkPHP
#
function version_gt {
  test "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1";
}
function checkPHP {
  if ! command -v php >/dev/null 2>&1; then
    echo ""
    echo ""
    echo "php must be installed and define in the \$PATH variable"
    echo ""
    echo ""
    exit 1
  fi
  phpver=`php -v |grep -Eow '^PHP [^ ]+' |gawk '{ print $2 }'`
  if version_gt 5.65 $phpver; then
    echo ""
    echo ""
    echo "php version must be greeter than 5.5"
    echo ""
    echo ""
    exit 1
  fi
}

#
# checkComposer
#
function checkConposer {
  if [ ! -f "scripts/composer.phar" ]; then
    cd scripts
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php
    rm composer-setup.php
    cd ..
  fi
}

#
# main
#
if [ "$1" = "" ]; then
    showHelp;
fi

case $1 in
  create )  create $2 $3
            ;;
  checkout ) checkout $2
            ;;
  build ) build
            ;;
  package ) package
            ;;
  deploy )  deploy
            ;;
  update )  update
            ;;
  site ) site $2
            ;;
       * )  
            echo "unknown command : $1"
            showHelp
            ;;
esac
exit 1

#
# create
#
function create {
  if [ "$1" = "" ]; then
      echo "project's name missing"
      showHelp;
  fi
  checkPHP
  if [ ! -f "composer.json" ] then
    if [ -d ".git" ] then
      echo ""
      echo ""
      echo "Can not create project from an existing git directory"
      echo ""
      echo ""
      exit 1
    fi
    checkGit
    git clone https://github.com/fauconv/indus_drupal8_angular2.git .
    rm -rf .git
  fi

  sed 's|"name" *: *".*"|"name": "$1",|' composer.json > composer.json2
  sed 's|"name" *: *".*"|"name": "$1",|' package.json > package.json2
  sed 's|"description" *: *".*"|"description": "$2",|' composer.json2 > composer.json
  sed 's|"description" *: *".*"|"description": "$2",|' package.json2 > package.json
  rm composer.json2 package.json
  install
  exit 0
}

#
# install
#
function install {
  checkComposer
  php scripts/composer.phar install
  vendor/bin/npm install
}

#
# build
#
function build {
  exit 1
}

#
# package
#
function package {
  exit 1
}

#
# deploy 
#
function deploy {
  exit 1
}

#
# update
#
function update {
  exit 1
}
