#!/bin/bash

#
# showHelp
#
function showHelp {
  echo ""
  echo ""
  echo "usage : $0 <comand> <args>"
  echo ""
  echo "Commands :"
  echo ""
  echo "  $0 create <project_name>  : create a drupal/angular project for development. You have to git init your project to save it after create "
  echo "  $0 install : install the project already created for development after a git clone of the project"
  echo "  $0 build   : compil and build project for development"
  echo "  $0 package : create a package for deployment in production"
  echo "  $0 deploy  : deploy the package in production (like install+build for dev)"
  echo "  $0 update  : update the project in production or dev"
  echo ""
  echo ""
  exit 0
}

#
# checkGit
#
function checkGit {
  if ! command -v git >/dev/null 2>&1; then
    echo ""
    echo ""
    echo "git must be installed and define in the \$PATH variable"
    echo ""
    echo ""
    exit 0
  fi
}

#
# checkPHP
#
function version_gt {
  test "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1";
}
function checkPHP {
  if ! command -v php >/dev/null 2>&1; then
    echo ""
    echo ""
    echo "php must be installed and define in the \$PATH variable"
    echo ""
    echo ""
    exit 0
  fi
  phpver=`php -v |grep -Eow '^PHP [^ ]+' |gawk '{ print $2 }'`
  if version_gt 5.65 $phpver; then
    echo ""
    echo ""
    echo "php version must be greeter than 5.5"
    echo ""
    echo ""
    exit 0
  fi
}

#
# checkComposer
#
function checkConposer {
  if [ ! -f "scripts/composer.phar" ] then
    cd scripts
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php
    rm composer-setup.php
    cd ..
  fi
}


#
# main
#
if [ "$1" = "" ]; then
    showHelp;
fi

case $1 in
  create )  create $2
            ;;
  install ) install
            ;;
  build ) build
            ;;
  package ) package
            ;;
  deploy )  deploy
            ;;
  update )  update
            ;;
       * )  
            echo "unknown command : $1"
            showHelp
            ;;
esac
exit 0

#
# create
#
function create {
  if [ "$1" = "" ]; then
      echo "project's name missing"
      showHelp;
  fi
  if [ ! -f "composer.json" ] then
    if [ -d ".git" ] then
      echo ""
      echo ""
      echo "Can not create project from an existing git directory"
      echo ""
      echo ""
      exit 0
    fi
    checkGit
    git clone https://github.com/fauconv/indus_drupal8_angular2.git .
    rm -rf .git
  fi
  sed 's|#|$1' composer.json > composer.json2
  rm composer.json
  mv composer.json2 composer.json
  exit 1
}

#
# create
#
function install {
  checkPHP
  checkComposer
  php scripts/composer.phar install
  vendor/bin/npm install
  exit 1
}

#
# build
#
function build {
  exit 1
}

#
# package
#
function package {
  exit 1
}

#
# deploy 
#
function deploy {
  exit 1
}

#
# update
#
function update {
  exit 1
}
