## YAML Template.
commands:
  - command: 'site:install'
    options:
        db-type: mysql
        db-host: 127.0.0.1
        db-name: drupal
        db-user: user
        db-pass: pass
        db-port: '3306'
        uri: 'http://localhost'

        site-name: '%{{name}}'
        site-mail: %{{mail}}
        account-name: %{{name_user}}
        account-mail: %{{mail_user}}
        account-pass: '%{{pass}}'
        langcode: %{{lang}}
    arguments:
      profile: '%{{profile}}'

## site name + site mail  + directory a mettre + lang
