## YAML Template.
commands:
  - command: 'site:install'
    options:
        db-type: '%{{db_type|mysql}}'
        db-host: '%{{db_host|127.0.0.1}}'
        db-name: '%{{db_name}}'
        db-user: '%{{db_user}}'
        db-pass: '%{{db_password}}'
        db-port: '%{{db_port|3306}}'
        uri: '%{{site_uri|http://localhost}}'

        site-name: '%{{{site_name}}'
        site-mail: '%{{site_mail}}'
        account-name: '${{ADMIN_NAME}}'
        account-mail: '%{{admin_mail}}'
        langcode: '%{{site_lang}}'
    arguments:
      profile: '${{SITE_PROFIL}}'

