#!/bin/bash
#+-----------------------------------------------------------+
#|                                                           |
#| Drush shortcut                                            |
#|                                                           |
#| To manage bug in composer                                 |
#| composer need to have bin directory in vendor             |
#|                                                           |
#+-----------------------------------------------------------+
#| version : 1                                               |
#+-----------------------------------------------------------+

#DCF paths
SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")
ABS_SCRIPT_PATH=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
source ${ABS_SCRIPT_PATH}/dcf_path

"${ABS_VENDOR_BIN_PATH}/npm" "$@"
