#!/bin/bash

#
# const
#
PHP_VER=5.5.9 #PHP minimum version for drupal
DRUPAL_ANGULAR_URL=https://github.com/fauconv/indus_drupal8_angular2.git
DRUPAL_ANGULAR_TAG=master

#
# showHelp
#
function showHelp {
  name=$(basename $0)
  echo ""
  echo ""
  echo "usage : $name <command> <args>"
  echo ""
  echo "* Commands :"
  echo ""
  echo "  $name create <params>   : create a multisite drupal project for development. (get the project skeleton from git)"
  echo "  $name deploy (dev | prod) : get common composer and npm packages for the project"
  echo "  $name site create <id> <canonical_url> : create a new website in the project for development. (create website skeleton)"
  echo "  $name site deploy (dev | prod) <id> : get specific composer and npm packages for the website"
  echo "  $name site install (dev|prod) <id> : install a site already created for development or production (drupal install of the website)"
  echo "  $name site build (dev|prod) <id>  : compil and build a site for frontend in development"
  echo "  $name package : create a package for deployment in production of a project without website."
  echo "  $name site package <id> : create a package for deployment in production of a specific website"
  echo "  $name update  : update the project in production or dev"
  echo "  $name site update <id> : update a site in production or dev"
  echo ""
  echo ""
  echo "* create :"
  echo ""
  echo "  $name create project-name [project-description]"
  echo ""
  echo ""
  exit 1
}

#
# checkGit
#
function checkGit {
  if ! command -v git >/dev/null 2>&1; then
    echo ""
    echo ""
    echo "git must be installed and define in the \$PATH variable"
    echo ""
    echo ""
    exit 1
  fi
}

#
# checkPHP
#
function version_gt {
  test "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1";
}
function checkPHP {
  if ! command -v php >/dev/null 2>&1; then
    echo ""
    echo ""
    echo "php must be installed and define in the \$PATH variable"
    echo ""
    echo ""
    exit 1
  fi
  phpver=`php -v |grep -Eow '^PHP [^ ]+' |gawk '{ print $2 }'`
  echo "Current PHP version : $phpver"
  if version_gt $PHP_VER $phpver; then
    echo ""
    echo ""
    echo "php version must be greeter than $PHP_VER"
    echo ""
    echo ""
    exit 1
  fi
}

#
# checkComposer
#
function checkConposer {
  echo "CheckComposer:"
  if [ ! -f "composer.json" ]; then
    echo ""
    echo ""
    echo "You must create a project first"
    echo ""
    echo ""
    exit 1
  fi
  if [ ! -f "scripts/composer.phar" ]; then
    cd scripts
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php composer-setup.php
    rm composer-setup.php
    cd ..
  fi
}

#
# deploy
#
function deploy {
  checkConposer
  if [ "$1" = "prod" ]; then
    echo "Composer install (prod):"
    php scripts/composer.phar install --no-dev
    echo "NPM install (prod) :"
    vendor/bin/npm install --only=prod --nodedir=vendor/bin --prefix=./web
  else
    echo "Composer install:"
    php scripts/composer.phar install
    echo "NPM install:"
    vendor/bin/npm install --nodedir=vendor/bin --prefix=./web
  fi
}

#
# create
#
function create {
  if [ "$2" = "" ]; then
      echo "project's name missing"
      showHelp;
  fi
  checkPHP
  if [ ! -f "composer.json" ]; then
    if [ -d ".git" ]; then
      echo ""
      echo ""
      echo "Can not create project from an existing git directory"
      echo ""
      echo ""
      exit 1
    fi
    checkGit
    echo "git clone $DRUPAL_ANGULAR_URL --single-branch --branch $DRUPAL_ANGULAR_TAG"
    git clone $DRUPAL_ANGULAR_URL --single-branch --branch $DRUPAL_ANGULAR_TAG clone
    rm -rf clone/.git
    mv clone/* . 2> /dev/null
    mv clone/.* . 2> /dev/null
    rm -rf clone
  fi
  echo "setup project $2..."
  sed "s|\"name\" *: *\".*\"|\"name\": \"$2\"|" composer.json > composer.json2
  sed "s|\"name\" *: *\".*\"|\"name\": \"$2\"|" package.json > package.json2
  sed "s|\"description\" *: *\".*\"|\"description\": \"$3\"|" composer.json2 > composer.json
  sed "s|\"description\" *: *\".*\"|\"description\": \"$3\"|" package.json2 > package.json
  rm composer.json2 package.json2
  rm $1
  chmod 755 scripts/project
}

#
# main
#
cd $(dirname $0)
if [ "$1" = "" ]; then
    showHelp;
fi

case $1 in
  create ) create $0 $2 $3
            ;;
  deploy ) cd ..;deploy $2
            ;;
       * )
            echo "unknown command : $1"
            showHelp
            ;;
esac
exit 0
