#!/bin/bash
#+-----------------------------------------------------------+
#|                                                           |
#| all DCF path                                              |
#| composer and drush dont like bin dir out of vendor dir    |
#|                                                           |
#+-----------------------------------------------------------+
#| version : 1                                               |
#+-----------------------------------------------------------+

CONFIG_PATH=config
DOCUMENT_ROOT=web
SITES_PATH=${DOCUMENT_ROOT}/sites
DOC_PATH=docs
VENDOR_PATH=vendor
VENDOR_BIN_PATH=${VENDOR_PATH}/bin
SCRIPTS_PATH=scripts #depth need to be only 1
FILES_PATH=files
TRANSLATIONS_PATH=${FILES_PATH}/translations

PATH_SCRIPT_PATH=$ABS_SCRIPT_PATH
if command -v 'cygpath' >/dev/null 2>&1; then
  ABS_SCRIPT_PATH=$(cygpath -m "$ABS_SCRIPT_PATH");
fi
ABS_DCF_PATH=$(dirname $ABS_SCRIPT_PATH)
PATH_DCF_PATH=$(dirname $PATH_SCRIPT_PATH)

ABS_CONFIG_PATH=${ABS_DCF_PATH}/${CONFIG_PATH}
ABS_DOCUMENT_ROOT=${ABS_DCF_PATH}/${DOCUMENT_ROOT}
ABS_SITES_PATH=${ABS_DCF_PATH}/${SITES_PATH}
ABS_DOC_PATH=${ABS_DCF_PATH}/${DOC_PATH}
ABS_VENDOR_PATH=${ABS_DCF_PATH}/${VENDOR_PATH}
ABS_VENDOR_BIN_PATH=${ABS_DCF_PATH}/${VENDOR_BIN_PATH}
PATH_VENDOR_BIN_PATH=${PATH_DCF_PATH}/${VENDOR_BIN_PATH}
ABS_SCRIPTS_PATH=${ABS_DCF_PATH}/${SCRIPTS_PATH}
