#!/bin/bash
#+-----------------------------------------------------------+
#|                                                           |
#| Module to add to standard drupal                          |
#|                                                           |
#|                                                           |
#+-----------------------------------------------------------+
#| version : ${VERSION_SCRIPT}                               |
#+-----------------------------------------------------------+

composer require -n --no-suggest \
drupal/admin_toolbar \
drupal/composer_manager \
drupal/module_filter \
drupal/menu_admin_per_menu \
drupal/plugin

